FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build   # assumes "build": "tsc" in package.json

FROM node:24-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY --from=builder /app/dist ./dist

ARG MONGO_URI
ARG MONGO_AUDIT_URI
ARG MONGO_AUDIT_DB
ARG JWT_ACCESS_SECRET
ARG CEREBRAS_API_KEY
ARG NODE_ENV
ARG PORT
ARG ALLOWED_HEADERS
ARG ALLOWED_ORIGINS
ARG BCRYPT_SALT_ROUNDS
ARG LOG_LEVEL
ARG TASKS_DAILY_LIMIT

# ENV MONGO_URI=$MONGO_URI \
    # MONGO_AUDIT_URI=$MONGO_AUDIT_URI\
    # MONGO_AUDIT_DB=$MONGO_AUDIT_DB\
    # JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET \
    # CEREBRAS_API_KEY=$CEREBRAS_API_KEY \
    # NODE_ENV=$NODE_ENV \
    # PORT=$PORT \
    # ALLOWED_HEADERS=$ALLOWED_HEADERS \
    # ALLOWED_ORIGINS=$ALLOWED_ORIGINS \
    # BCRYPT_SALT_ROUNDS=$BCRYPT_SALT_ROUNDS \
    # LOG_LEVEL=$LOG_LLEVEL \
    # TASKS_DAILY_LIMIT=$TASKS_DAILY_LIMIT \
    # RAILWAY_PUBLIC_DOMAIN=$RAILWAY_PUBLIC_DOMAIN \
    # RAILWAY_PRIVATE_DOMAIN=$RAILWAY_PRIVATE_DOMAIN \
    # RAILWAY_PROJECT_NAME=$RAILWAY_PROJECT_NAME \
    # RAILWAY_ENVIRONMENT_NAME=$RAILWAY_ENVIRONMENT_NAME \
    # RAILWAY_SERVICE_NAME=$RAILWAY_SERVICE_NAME \
    # RAILWAY_PROJECT_ID=$RAILWAY_PROJECT_ID \
    # RAILWAY_ENVIRONMENT_ID=$RAILWAY_ENVIRONMENT_ID \
    # RAILWAY_SERVICE_ID=$RAILWAY_SERVICE_ID


EXPOSE 3000

CMD ["node", "dist/index.js"]
