export const emailClasses = {
    "official": "If it contains financial/legal terms",
    "ad": "If it contains promotional terms"
}

export const officialKeywords: string[] = [
  "invoice", "receipt", "statement", "account", "payment", "transaction", "bill",
  "order", "confirmation", "shipment", "tracking", "delivery", "official", "notice",
  "report", "balance", "due", "statement_date", "purchase", "subscription", "refund",
  "credit", "debit", "tax", "fee", "charge", "amount", "total", "subtotal", "itemized",
  "quantity", "price", "billing", "customer", "vendor", "supplier", "reference", "number",
  "date", "terms", "conditions", "policy", "authorization", "approval", "statement_id",
  "transaction_id", "order_id", "invoice_id", "payment_id", "receipt_id", "delivery_id",
  "shipment_id", "purchase_order", "po_number", "amount_due", "due_date", "balance_due",
  "overdue", "late_fee", "tax_amount", "tax_id", "vat", "gst", "hst", "service_fee", "shipping_fee",
  "handling_fee", "processing_fee", "payment_method", "bank", "account_number", "routing_number",
  "iban", "swift_code", "reference_number", "memo", "note", "customer_id", "vendor_id",
  "client_id", "transaction_date", "payment_date", "billing_date", "invoice_date", "issue_date",
  "due_amount", "total_amount", "paid_amount", "outstanding", "statement_period", "start_date",
  "end_date", "period", "billing_cycle", "cycle", "confirmation_number", "authorization_code",
  "approval_code", "tracking_number", "delivery_date", "shipment_date", "dispatch_date",
  "received_date", "processed_date", "order_date", "purchase_date", "submitted_date",
  "document_number", "file_number", "reference_code", "customer_name", "vendor_name",
  "client_name", "company_name", "organization", "institution", "department", "branch",
  "office", "location", "address", "contact", "email", "phone", "fax", "website",
  "details", "information", "summary", "record", "log", "history", "statement_summary",
  "report_summary", "account_summary", "ledger", "journal", "voucher", "payment_voucher",
  "receipt_voucher", "credit_note", "debit_note", "remittance", "transfer", "settlement",
  "reconciliation", "reconciled", "approved", "verified", "validated", "processed",
  "completed", "pending", "in_progress", "on_hold", "canceled", "voided", "returned",
  "refunded", "adjustment", "correction", "amendment", "modification", "update",
  "change", "revision", "version", "copy", "original", "duplicate", "attachment",
  "document", "file", "record", "archive", "statement_file", "invoice_file",
  "payment_file", "transaction_file", "account_file", "report_file", "ledger_file",
  "journal_file", "voucher_file", "credit_file", "debit_file", "remittance_file",
  "transfer_file", "settlement_file", "reconciliation_file", "approved_file",
  "verified_file", "validated_file", "processed_file", "completed_file", "pending_file",
  "on_hold_file", "canceled_file", "voided_file", "returned_file", "refunded_file",
  "adjustment_file", "correction_file", "amendment_file", "modification_file",
  "update_file", "change_file", "revision_file", "version_file", "copy_file", "original_file",
  "duplicate_file", "attachment_file", "invoice_number", "bill_number", "statement_number",
  "transaction_number", "payment_number", "order_number", "purchase_number", "reference_number_1",
  "reference_number_2", "reference_number_3", "amount_1", "amount_2", "amount_3", "tax_1",
  "tax_2", "tax_3", "fee_1", "fee_2", "fee_3", "charge_1", "charge_2", "charge_3", "total_1",
  "total_2", "total_3", "balance_1", "balance_2", "balance_3", "due_1", "due_2", "due_3",
  "payment_method_1", "payment_method_2", "payment_method_3", "bank_1", "bank_2", "bank_3",
  "account_number_1", "account_number_2", "account_number_3", "routing_number_1", "routing_number_2",
  "routing_number_3", "iban_1", "iban_2", "iban_3", "swift_code_1", "swift_code_2", "swift_code_3",
  "memo_1", "memo_2", "memo_3", "note_1", "note_2", "note_3", "statement_id_1", "statement_id_2",
  "statement_id_3", "invoice_id_1", "invoice_id_2", "invoice_id_3", "transaction_id_1",
  "transaction_id_2", "transaction_id_3", "payment_id_1", "payment_id_2", "payment_id_3",
  "receipt_id_1", "receipt_id_2", "receipt_id_3", "delivery_id_1", "delivery_id_2", "delivery_id_3",
  "purchase_order_1", "purchase_order_2", "purchase_order_3", "po_number_1", "po_number_2", "po_number_3",
  "amount_due_1", "amount_due_2", "amount_due_3", "balance_due_1", "balance_due_2", "balance_due_3",
  "overdue_1", "overdue_2", "overdue_3", "late_fee_1", "late_fee_2", "late_fee_3", "tax_amount_1",
  "tax_amount_2", "tax_amount_3", "tax_id_1", "tax_id_2", "tax_id_3", "vat_1", "vat_2", "vat_3",
  "gst_1", "gst_2", "gst_3", "hst_1", "hst_2", "hst_3", "service_fee_1", "service_fee_2", "service_fee_3",
  "shipping_fee_1", "shipping_fee_2", "shipping_fee_3", "handling_fee_1", "handling_fee_2", "handling_fee_3",
  "processing_fee_1", "processing_fee_2", "processing_fee_3", "transaction_fee", "payment_confirmation",
  "bank_transfer", "check", "cheque", "remittance_advice", "settlement_note", "payment_confirmation_note",
  "delivery_note", "goods_receipt", "goods_issue", "invoice_copy", "receipt_copy", "account_statement",
  "ledger_entry", "journal_entry", "voucher_entry", "credit_note_copy", "debit_note_copy", "reconciliation_statement",
  "approval_note", "authorization_note", "verification_note", "processing_note", "completed_note",
  "pending_note", "on_hold_note", "cancellation_note", "void_note", "return_note", "refund_note",
  "adjustment_note", "correction_note", "amendment_note", "modification_note", "update_note",
  "revision_note", "version_note", "original_note", "duplicate_note", "attachment_note",
  "document_note", "file_note", "record_note", "archive_note", "statement_file_note",
  "invoice_file_note", "payment_file_note", "transaction_file_note", "account_file_note",
  "report_file_note", "ledger_file_note", "journal_file_note", "voucher_file_note", "credit_file_note",
  "debit_file_note", "remittance_file_note", "transfer_file_note", "settlement_file_note",
  "reconciliation_file_note", "approved_file_note", "verified_file_note", "validated_file_note",
  "processed_file_note", "completed_file_note", "pending_file_note", "on_hold_file_note",
  "canceled_file_note", "voided_file_note", "returned_file_note", "refunded_file_note",
  "adjustment_file_note", "correction_file_note", "amendment_file_note", "modification_file_note",
  "update_file_note", "change_file_note", "revision_file_note", "version_file_note", "copy_file_note",
  "original_file_note", "duplicate_file_note", "attachment_file_note", "invoice_number_1",
  "invoice_number_2", "invoice_number_3", "bill_number_1", "bill_number_2", "bill_number_3",
  "statement_number_1", "statement_number_2", "statement_number_3", "transaction_number_1",
  "transaction_number_2", "transaction_number_3", "payment_number_1", "payment_number_2", "payment_number_3",
  "order_number_1", "order_number_2", "order_number_3", "purchase_number_1", "purchase_number_2",
  "purchase_number_3", "reference_number_1", "reference_number_2", "reference_number_3", "amount_1",
  "amount_2", "amount_3", "tax_1", "tax_2"]

export const promotionalKeywords: string[] = [
  "sale", "discount", "offer", "promo", "deal", "coupon", "voucher", "limited", "exclusive",
  "newsletter", "advertisement", "ad", "promotion", "buy now", "flash sale", "free", "win",
  "gift", "special", "subscribe", "clearance", "bundle", "deal of the day", "hot deal",
  "today only", "best price", "save", "rebate", "reward", "bonus", "loyalty", "membership",
  "early access", "pre-order", "new arrival", "exclusive offer", "flash offer", "limited edition",
  "clearance sale", "mega sale", "discount code", "promo code", "free shipping", "free trial",
  "trial offer", "trial period", "gift card", "gift voucher", "cashback", "special promotion",
  "instant savings", "deal alert", "offer ends", "today only", "online exclusive", "limited stock",
  "shop now", "act fast", "while supplies last", "final sale", "exclusive deal", "special offer",
  "best deal", "hot offer", "deal of the week", "bonus offer", "freebie", "buy one get one",
  "bogo", "limited time", "mega offer", "save big", "discounted", "voucher code", "coupon code",
  "members only", "vip offer", "exclusive access", "price drop", "sale alert", "clearance items",
  "weekly deal", "daily deal", "seasonal sale", "promotion alert", "limited quantity",
  "special price", "instant offer", "offer inside", "unlock deal", "secret deal", "special discount",
  "limited offer", "hot discount", "exclusive savings", "members discount", "reward points",
  "redeem", "claim offer", "limited time offer", "holiday sale", "black friday", "cyber monday",
  "end of season", "price cut", "special deal", "shop the sale", "today only deal", "flash discount",
  "early bird", "vip access", "early access offer", "insider deal", "exclusive promotion",
  "free bonus", "add-on offer", "price slash", "special promotion", "mega discount",
  "super sale", "extra savings", "cashback offer", "redeem now", "limited edition offer",
  "exclusive voucher", "deal inside", "offer expires", "hurry", "last chance", "time-limited",
  "promo alert", "discount alert", "exclusive event", "offer for you", "reward offer", "members special",
  "bonus deal", "limited release", "special item", "deal code", "promo code inside", "free gift",
  "bundle deal", "hot sale", "special savings", "offer today", "today's deal", "weekly promotion",
  "vip deal", "exclusive bundle", "clearance offer", "shop and save", "bonus points", "buy more save more",
  "extra bonus", "special reward", "instant deal", "limited edition sale", "deal alert", "hot discount",
  "mega offer today", "exclusive flash sale", "price drop alert", "early bird offer", "free trial offer",
  "gift with purchase", "exclusive gift", "flash promotion", "last day offer", "special coupon",
  "deal of the month", "offer code", "holiday offer", "clearance deal", "discount promotion",
  "mega discount today", "vip special", "limited stock alert", "shop limited", "super deal", "special bundle",
  "exclusive savings today", "offer bonus", "instant discount", "special price today", "bundle promotion",
  "members deal", "reward code", "redeem offer", "exclusive points", "bonus code", "limited flash deal",
  "secret discount", "vip bonus", "deal bonus", "today's offer", "discounted price", "offer inside email",
  "exclusive coupon", "hot bundle", "limited edition coupon", "extra offer", "bonus reward", "special sale",
  "flash deal today", "special event", "exclusive sale", "today's special", "offer now", "deal now",
  "hot today", "save today", "special reward today", "exclusive offer today", "limited offer today",
  "deal of the hour", "flash offer now", "instant savings today", "exclusive discount", "special bundle today",
  "bonus today", "vip offer today", "members exclusive", "offer alert", "hot deal alert", "discount alert today",
  "exclusive promotion today", "mega deal today", "daily discount", "deal of the day today", "limited time deal",
  "special offer alert", "instant deal today", "vip bundle", "exclusive bundle today", "flash discount today",
  "last chance deal", "final offer", "super discount", "exclusive event today", "holiday promotion",
  "special holiday deal", "mega sale today", "flash sale today", "exclusive flash offer", "discount code today",
  "promo code today", "deal code today", "coupon code today", "reward points today", "redeem now today",
  "limited quantity offer", "special price alert", "bonus points today", "members bonus", "vip reward",
  "exclusive bonus offer", "instant bonus", "daily deal today", "offer expires today", "flash promo", "last day deal",
  "today only promotion", "bonus gift", "free item", "freebie today", "buy one get one today", "bogo today",
  "special bundle offer", "limited edition bonus", "exclusive freebie", "hot bonus today", "super offer today",
  "holiday deal today", "special holiday offer", "exclusive holiday promotion", "deal today", "special reward today",
  "exclusive gift today", "vip deal today", "members reward today", "redeem reward today", "special discount today",
  "flash sale alert", "limited time flash", "exclusive flash", "mega discount alert", "special offer code",
  "exclusive offer code", "vip promo", "members promo", "bonus promo", "redeem promo", "daily promo",
  "flash promo today", "limited offer code", "special coupon today", "exclusive coupon today", "hot coupon",
  "deal coupon", "bonus coupon", "reward coupon", "promo coupon", "holiday promo", "holiday discount",
  "exclusive holiday offer", "vip holiday deal", "members holiday reward", "mega bundle", "super bundle",
  "flash bundle", "deal bundle", "exclusive bundle offer", "limited edition bundle", "special bundle deal",
  "vip bundle today", "bonus bundle", "redeem bundle", "offer bundle today", "daily bundle", "limited edition deal",
  "exclusive limited", "flash limited", "super limited offer", "mega limited offer", "special limited offer",
  "holiday bundle", "exclusive holiday bundle", "vip holiday bundle", "members holiday bundle",
  "bonus holiday", "free holiday gift", "redeem holiday", "daily deal alert", "flash sale alert today",
  "special flash sale", "exclusive flash sale offer", "vip flash sale", "limited flash sale", "hot flash deal",
  "mega flash sale", "super flash sale", "instant flash deal", "bonus flash offer", "redeem flash offer",
  "daily flash offer", "flash promotion today", "exclusive flash promotion", "holiday flash sale",
  "vip flash promotion", "members flash promo", "bonus flash promo", "special flash promo",
  "limited time flash promo", "mega flash promo", "super flash promo", "instant flash promo",
  "exclusive instant promo", "daily instant deal", "daily instant offer", "instant bonus deal",
  "instant bonus offer", "bonus instant deal", "bonus instant offer", "redeem instant bonus",
  "redeem instant deal", "redeem instant offer", "special instant bonus", "special instant deal",
  "vip instant offer", "members instant bonus", "members instant deal", "exclusive members offer",
  "exclusive members deal", "exclusive members bonus", "holiday instant offer", "holiday instant deal",
  "holiday bonus offer", "holiday bonus deal", "exclusive holiday instant", "flash deal bonus",
  "flash deal promo", "flash deal reward", "flash deal gift", "bonus gift today", "redeem gift today",
  "special reward gift", "special reward deal", "vip bonus reward", "vip bonus gift", "members bonus reward",
  "members bonus gift", "daily reward gift", "daily reward bonus", "exclusive daily reward", "daily bonus offer",
  "daily bonus deal", "daily deal bonus", "daily promo bonus", "daily flash reward", "daily flash bonus",
  "daily flash gift", "daily flash deal", "daily flash promo", "instant deal gift", "instant deal bonus",
  "instant deal reward", "instant promo bonus", "instant promo reward", "instant promo gift", "redeem instant gift",
  "redeem instant reward", "redeem instant bonus", "exclusive instant reward", "exclusive instant deal",
  "exclusive instant gift", "bonus instant gift", "bonus instant reward", "bonus instant deal", "vip instant bonus",
  "vip instant reward", "vip instant gift", "members instant reward", "members instant gift", "members instant bonus",
  "holiday instant bonus", "holiday instant reward", "holiday instant gift", "holiday instant deal", "daily instant gift",
  "daily instant reward", "daily instant deal", "daily instant promo", "daily instant offer", "daily instant reward",
  "daily instant gift", "daily instant bonus", "daily instant deal", "daily flash reward", "daily flash bonus",
  "daily flash gift", "daily flash promo", "daily flash deal"
];
